spring:
  application:
    name: Eureka-Hello-Client
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:hhttp://eureka-server-mukul-k.9a6d.starter-us-east-1a.openshiftapps.com/}
  instance:
    preferIpAddress: true
   
info:
    app:
      name: Eureka-Hello-Client
      description: This is my First Spring Boot Eureka Hello client Microservice.
      version: 1.0
   
