spring:
  application:
    name: Eureka-Hello-Client
eureka:
   instance:
      preferIpAddress: false
   client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

info:
    app:
      name: Eureka-Hello-Client
      description: This is my First Spring Boot Eureka Hello client Microservice.
      version: 1.0
   
